
import type { ReactElement } from 'react'
import {
  SiPython,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiFastapi,
  SiFlask,
  SiDjango,
  SiDotnet,
  SiPandas,
  SiNumpy,
  SiTensorflow,
  SiFirebase,
  SiDocker,
  SiGithubactions,
  SiMetabase,
  SiApacheairflow,
  SiDbt,
  SiJupyter,
  SiOpencv,
  SiScikitlearn,
  SiGit,
  SiJira,
  SiConfluence,
  SiNotion,
  SiFigma,
  SiPostgresql,
  SiTailwindcss,
  SiR,
} from 'react-icons/si'
import {
  FaCode,
  FaChartLine,
  FaCloud,
  FaDatabase,
  FaBrain,
  FaCodeBranch,
  FaServer,
} from 'react-icons/fa6'

const baseIconProps = { size: 14 }

export const techIcons: Record<string, ReactElement> = {
  Python: <SiPython {...baseIconProps} />,
  'C#': <FaCode size={12} />,
  'JavaScript / TypeScript': <SiTypescript {...baseIconProps} />,
  JavaScript: <SiJavascript {...baseIconProps} />,
  TypeScript: <SiTypescript {...baseIconProps} />,
  R: <SiR {...baseIconProps} />,
  React: <SiReact {...baseIconProps} />,
  FastAPI: <SiFastapi {...baseIconProps} />,
  Flask: <SiFlask {...baseIconProps} />,
  Django: <SiDjango {...baseIconProps} />,
  '.NET': <SiDotnet {...baseIconProps} />,
  Pandas: <SiPandas {...baseIconProps} />,
  NumPy: <SiNumpy {...baseIconProps} />,
  TensorFlow: <SiTensorflow {...baseIconProps} />,
  Firebase: <SiFirebase {...baseIconProps} />,
  Docker: <SiDocker {...baseIconProps} />,
  'GitHub Actions': <SiGithubactions {...baseIconProps} />,
  'Azure DevOps': <FaCloud size={12} />,
  'Power BI': <FaChartLine size={12} />,
  Metabase: <SiMetabase {...baseIconProps} />,
  Airflow: <SiApacheairflow {...baseIconProps} />,
  'Apache Airflow': <SiApacheairflow {...baseIconProps} />,
  dbt: <SiDbt {...baseIconProps} />,
  'ETL/ELT': <FaCodeBranch size={12} />,
  'Modelado Dimensional': <FaDatabase size={12} />,
  'Dimensional Modeling': <FaDatabase size={12} />,
  'Jupyter Notebook': <SiJupyter {...baseIconProps} />,
  OpenCV: <SiOpencv {...baseIconProps} />,
  'Scikit-learn': <SiScikitlearn {...baseIconProps} />,
  MLOps: <FaBrain size={12} />,
  'Modelos Predictivos': <FaBrain size={12} />,
  'Predictive Models': <FaBrain size={12} />,
  Git: <SiGit {...baseIconProps} />,
  Jira: <SiJira {...baseIconProps} />,
  Confluence: <SiConfluence {...baseIconProps} />,
  Notion: <SiNotion {...baseIconProps} />,
  Figma: <SiFigma {...baseIconProps} />,
  PostgreSQL: <SiPostgresql {...baseIconProps} />,
  'SQL Server': <FaServer size={12} />,
  'Tailwind CSS': <SiTailwindcss {...baseIconProps} />,
  SQL: <FaDatabase size={12} />,
  'Sistemas Distribuidos': <FaCloud size={12} />,
  'Arquitectura de Software': <FaCodeBranch size={12} />,
  DAX: <FaChartLine size={12} />,
  'Modelado de Datos': <FaDatabase size={12} />,
  'Data Modeling': <FaDatabase size={12} />,
}

export const getTechIcon = (key: string): ReactElement | undefined => techIcons[key]
